WANDB_CACHE_DIR=./wandb_cache/ python -m ipdb -c c train_wandb.py --add_descriptive_test=False --add_discriminative_test=False --agent_loss_type=Hinge --agent_nbr_latent_dim=32 \
--arch=BN+BetaVAEEncoderOnly3x3 --baseline_only=False \
--nbr_experience_repetition=1 --batch_size=32 \
--dataset=3DShapesPyBullet --dataset_length=4096 \
--descriptive=True --descriptive_ratio=0 \
--dis_metric_resampling=True --distractor_sampling=uniform \
--dropout_prob=0 --egocentric=False --egocentric_tr_degrees=15 --egocentric_tr_xy=0.125 --emb_dropout_prob=0.0 \
--epoch=201 --graphtype=obverter --lr=0.0001 --max_sentence_length=10 \
--metric_active_factors_only=True --metric_batch_size=64 --dis_metric_epoch_period=10 --metric_epoch_period=10 --metric_resampling=True --mini_batch_size=64 \
--nb_3dshapespybullet_colors=10 --nb_3dshapespybullet_samples=1 --nb_3dshapespybullet_shapes=10 --nb_3dshapespybullet_train_colors=5 \
--nbr_discriminative_test_distractors=7 --nbr_distractors=31 \
--nbr_eval_points=200 --nbr_train_points=1000 \
--object_centric=False --obverter_nbr_games_per_round=64 \
--obverter_use_decision_head=False --obverter_learn_not_target_logit=True \
--obverter_nbr_head_outputs=2 --use_obverter_sampling=False --obverter_sampling_round_alternation_only=True --obverter_sampling_repeat_experiences=False \
--obverter_threshold_to_stop_message_generation=0.75 --obverter_use_residual_connections=False \
--parallel_TS_worker=32 --parent_folder=./3dshapes_obverter_replication_test \
--resizeDim=64 --seed=11 --shared_architecture=False \
--symbol_embedding_size=64 --symbol_processing_nbr_hidden_units=64 \
--synthetic_progression_end=10 --train_test_split_strategy=combinatorial2-FloorHue-2-S2-WallHue-2-S2-ObjectHue-2-S2-Scale-8-N-Shape-1-N-Orientation-3-N \
--use_cuda=True --vae_factor_gamma=0 --vae_gaussian=False --vae_lambda=0 --vae_nbr_latent_dim=32 \
--visual_context_consistent_obverter=False --use_utterance_conditioned_threshold=False \
--vocab_size=20 --with_BN_in_obverter_decision_head=False --with_DP_in_obverter_decision_head=False \
--with_baseline=False --with_color_jitter_augmentation=False --with_gaussian_blur_augmentation=True \
--with_classification_test=True --classification_test_nbr_class=10 --classification_test_loss_lambda=1.0 --with_attached_classification_heads=False \
--use_aitao=False --use_priority=False --aitao_max_similarity_ratio=10.0 --aitao_target_unique_prod_ratio=100.0 --aitao_language_similarity_sampling_epoch_period=1 \
--object_centric_version=2 --descriptive_version=1 

