WANDB_CACHE_DIR=./wandb_cache/ python -m ipdb -c c train_wandb.py --add_descriptive_test=False --add_discriminative_test=False --agent_loss_type=NLL --agent_nbr_latent_dim=32 \
--arch=BN+BetaVAEEncoderOnly3x3 --baseline_only=False \
--nbr_experience_repetition=1 --batch_size=64 \
--dataset=3DShapesPyBullet --dataset_length=4096 \
--descriptive=True --descriptive_ratio=0 \
--dis_metric_resampling=True --distractor_sampling=uniform \
--dropout_prob=0 --egocentric=False --egocentric_tr_degrees=5 --egocentric_tr_xy=0.125 --emb_dropout_prob=0.0 \
--epoch=101 --graphtype=obverter --lr=0.0001 --max_sentence_length=20 \
--metric_active_factors_only=True --metric_batch_size=64 --metric_epoch_period=5 --metric_resampling=True --mini_batch_size=64 \
--nb_3dshapespybullet_colors=10 --nb_3dshapespybullet_samples=100 --nb_3dshapespybullet_shapes=10 --nb_3dshapespybullet_train_colors=8 \
--nbr_discriminative_test_distractors=7 --nbr_distractors=0 \
--nbr_eval_points=2000 --nbr_train_points=2000 \
--object_centric=True --obverter_nbr_games_per_round=32 \
--obverter_use_decision_head=True --obverter_learn_not_target_logit=True \
--obverter_nbr_head_outputs=2 --use_obverter_sampling=False --obverter_sampling_round_alternation_only=True --obverter_sampling_repeat_experiences=True \
--obverter_threshold_to_stop_message_generation=0.95 --obverter_use_residual_connections=False \
--parallel_TS_worker=32 --parent_folder=./3dshapes_obverter_replication_test \
--resizeDim=64 --seed=11 --shared_architecture=False \
--symbol_embedding_size=64 --symbol_processing_nbr_hidden_units=64 \
--synthetic_progression_end=10 --train_test_split_strategy=combinatorial2-FloorHue-2-S2-WallHue-2-S2-ObjectHue-2-S2-Scale-8-N-Shape-1-N-Orientation-3-N \
--use_cuda=True --vae_factor_gamma=0 --vae_gaussian=False --vae_lambda=0 --vae_nbr_latent_dim=32 \
--visual_context_consistent_obverter=False --use_utterance_conditioned_threshold=False \
--vocab_size=10 --with_BN_in_obverter_decision_head=False --with_DP_in_obverter_decision_head=False \
--with_baseline=False --with_color_jitter_augmentation=False --with_gaussian_blur_augmentation=True \
--with_classification_test=True --classification_test_nbr_class=10 --classification_test_loss_lambda=1.0 --with_attached_classification_heads=False \
--use_aitao=False --use_priority=False --aitao_max_similarity_ratio=75.0 --aitao_target_unique_prod_ratio=80.0 --aitao_language_similarity_sampling_epoch_period=5 \
--object_centric_version=2 --descriptive_version=2 

