WANDB_CACHE_DIR=./wandb_cache/ python -m ipdb -c c train_wandb.py \
--project="COMPO+DIS+SYS-DEBUG" \
--seed=31 \
--use_cuda=True \
--object_centric_version=2 \
--descriptive_version=1 \
--dataloader_num_worker=2 \
--descriptive=True --descriptive_ratio=0 \
--object_centric=True \
--nbr_distractors=32 \
--resizeDim="-1" \
--shared_architecture=False \
--with_LN_in_listener_only=False \
--iterated_learning_scheme=False \
--iterated_learning_period=64 \
--listener_weight_decay_factor=0.0 \
--speaker_weight_decay_factor=0.0 \
--agent_weight_decay_exceptions="tau_fc,not_target_logit" \
--add_descriptive_test=True \
--add_discriminative_test=False --nbr_discriminative_test_distractors=7 \
--agent_loss_type=Impatient+Hinge --agent_nbr_latent_dim=32 \
--arch="MLP" --baseline_only=False \
--lr=0.0005 --weight_decay=0.0 \
--with_logits_mdl_principle=True \
--logits_mdl_principle_factor="neg-10-1" \
--logits_mdl_principle_use_inst_accuracy=True \
--logits_mdl_principle_accuracy_threshold=0 \
--logits_mdl_principle_normalization=True \
--logits_mdl_principle_entr_reg_factor="0.0" \
--logits_mdl_principle_entr_reg_masking=False \
--nbr_experience_repetition=1 --batch_size=128 \
--dataset=SCS --dataset_length=0 \
--scs_use_ohe_latent=True \
--scs_nbr_latents=4 --scs_min_nbr_values_per_latent=4 \
--scs_max_nbr_values_per_latent=4 --scs_nbr_object_centric_samples=16 \
--nb_3dshapespybullet_colors=10 --nb_3dshapespybullet_samples=10 \
--nb_3dshapespybullet_shapes=10 --nb_3dshapespybullet_train_colors=5 \
--dis_metric_resampling=True --distractor_sampling=uniform \
--dropout_prob=0 --emb_dropout_prob=0.0 \
--egocentric=False --egocentric_tr_degrees=15 --egocentric_tr_xy=0.125 \
--epoch=16001 --graphtype=straight_through_gumbel_softmax \
--max_sentence_length=10 --vocab_size=20 \
--metric_active_factors_only=True --metric_batch_size=64 \
--dis_metric_epoch_period=20 --metric_epoch_period=5 \
--metric_resampling=True --mini_batch_size=64 \
--nbr_eval_points=400 --nbr_train_points=500 \
--obverter_nbr_games_per_round=32 \
--obverter_use_decision_head=False --obverter_learn_not_target_logit=True \
--obverter_nbr_head_outputs=2 --use_obverter_sampling=False \
--obverter_sampling_round_alternation_only=False --obverter_sampling_repeat_experiences=False \
--obverter_threshold_to_stop_message_generation=0.95 --obverter_use_residual_connections=False \
--parallel_TS_worker=8 --parent_folder=./scs_stgs_test \
--symbol_embedding_size=64 --symbol_processing_nbr_hidden_units=256 \
--synthetic_progression_end=10 \
--train_test_split_strategy="combinatorial2-Y-8-S2-X-8-S2-Orientation-4-N-Scale-2-S1-Shape-1-S1" \
--vae_factor_gamma=0 --vae_gaussian=False --vae_lambda=0 --vae_nbr_latent_dim=32 \
--visual_context_consistent_obverter=False --use_utterance_conditioned_threshold=False \
--with_BN_in_obverter_decision_head=False --with_DP_in_obverter_decision_head=False \
--with_baseline=False --with_color_jitter_augmentation=False \
--with_gaussian_blur_augmentation=False \
--with_classification_test=True --classification_test_nbr_class=16 \
--classification_test_loss_lambda=1.0 --with_attached_classification_heads=False \
--use_aitao=False --use_priority=False \
--aitao_max_similarity_ratio=10.0 \
--aitao_target_unique_prod_ratio=100.0 \
--aitao_language_similarity_sampling_epoch_period=1 

#--synthetic_progression_end=10 --train_test_split_strategy=combinatorial2-FloorHue-2-S2-WallHue-2-S2-ObjectHue-2-S2-Scale-8-N-Shape-1-N-Orientation-3-N \

