#!/bin/sh

#SBATCH --job-name=Paper01a_Test_Inter_Sparse_BN+CNN3x3_B2
#SBATCH	--mail-type=ALL
#SBATCH	--mail-user=kyd500@york.ac.uk
#SBATCH --account=cs-dclabs-2019
#SBATCH	--ntasks=1
#SBATCH	--cpus-per-task=10
#SBATCH	--mem=64gb
#SBATCH --partition=week
#SBATCH --time=96:00:00
#SBATCH --gres=gpu:1

source activate RG
cd /users/kyd500/scratch/git/ReferentialGym/zoo/referential-games+st-gs/
./exp_inter_attr2_X+Y_sparse.sh 0 BN+CNN3x3 47 63 2

