python example_dSprites_DualLabeled_multi_head_lstm_cnn_agents_splitted_extra.py --seed 10 --arch CoordResNet18AvgPooled-2
python example_dSprites_DualLabeled_multi_head_lstm_cnn_agents_splitted_extra.py --seed 20 --arch CoordResNet18AvgPooled-2
python example_dSprites_DualLabeled_multi_head_lstm_cnn_agents_splitted_extra.py --seed 30 --arch CoordResNet18AvgPooled-2
python example_dSprites_DualLabeled_multi_head_lstm_cnn_agents_splitted_extra.py --seed 40 --arch CoordResNet18AvgPooled-2
python example_dSprites_DualLabeled_multi_head_lstm_cnn_agents_splitted_extra.py --seed 50 --arch CoordResNet18AvgPooled-2