python example_dSprites_DualLabeled_multi_head_lstm_cnn_agents_splitted_extra.py --seed 10 --arch ResNet18AvgPooled-2
python example_dSprites_DualLabeled_multi_head_lstm_cnn_agents_splitted_extra.py --seed 20 --arch ResNet18AvgPooled-2
python example_dSprites_DualLabeled_multi_head_lstm_cnn_agents_splitted_extra.py --seed 30 --arch ResNet18AvgPooled-2
python example_dSprites_DualLabeled_multi_head_lstm_cnn_agents_splitted_extra.py --seed 40 --arch ResNet18AvgPooled-2
python example_dSprites_DualLabeled_multi_head_lstm_cnn_agents_splitted_extra.py --seed 50 --arch ResNet18AvgPooled-2